# Workflow to test the USBIP client

name: USBIP CDC Client
on: push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        architecture: "x64"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tool_requirements.txt
    - name: lint
      run: |
        pylint *.py
    - name: Test with pytest
      run: |
        chmod +x run_pytest.sh
        ./run_pytest.sh
