# Workflow to test the USBIP client

name: USBIP CDC Client
on: push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requirements.txt
        pip install tool_requirements.txt
    - name: Lint
      run: |
        pylint *.py
    - name: Test with pytest
      run: |
        pytest
