# Workflow to test the USBIP client

name: USBIP CDC Client
on: push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        architecture: "x64"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tool_requirements.txt
    - name: lint
      run: |
        pylint *.py
    - name: Test & generate coverage
      run: |
        chmod +x run_pytest.sh
        ./run_pytest.sh
    - name: Generate Coverage badge
      uses: tj-actions/coverage-badge-py@v2
    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v16
      id: verify-changed-files
      with:
        # If this file has changed, we want to re-commit to the store
        files: coverage.svg

    - name: Commit files
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.git
        git config --local user.name "github-actions[bot]"
        git add coverage.svg
        git commit -am "Updated coverage.svg"

    - name: Push changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.github_token }}
        branch: ${{ github.ref }}
